
#General settings
[General]
	#Mobs that are exempt from AI modifications [default: [minecraft:iron_golem]
	AI_Blacklist = ["minecraft:iron_golem"]
	#Prevents players skipping the night through sleep [default: false]
	allowSleep = false
	#Awareness Radius [default: 64]
	#Range: > 0
	awarenessRadius = 64
	#The interval in which 'hard' days will occur where mob spawning is increased and lighting is ignored (0 = off, default = 8/full moon) [default: 8]
	#Range: > 0
	hardcoreDayCycle = 8
	#Maximum number of attackers per target [default: 16]
	#Range: 0 ~ 128
	pathingCap = 16
	#Temporary invulnerability in ticks when respawning and teleporting [default: 200]
	#Range: > 0
	resistanceCooldown = 200
	#Xray Distance [default: 64]
	#Range: > 0
	xrayDistance = 64

#Attack settings
[Attack]
	#Allows mobs to attack villagers as they would players [default: true]
	attackPets = true
	#Everyone one and everything is a target [default: false]
	attackEverything = false
	#Mobs are passive until provoked [default: false]
	neutralMobs = false
	#Mobs will strafe more than normal and avoid imminent explosions [default: true]
	attackEvasion = true
	#Animals will fight back if provoked [default: true]
	animalsAttack = true

#Advanced settings
[Advanced]
	#List of mobs that can dig through blocks [default: [minecraft:zombie]
	diggerMobs = ["minecraft:zombie"]
	#List of blocks that digger mobs are forbidden from digging (Format: 'minecraft:wool' prefix with # if mentioning a block tag)
	diggingBlacklist = []
	#The item given to a digger 5% of the time [default: minecraft:iron_pickaxe]
	diggerItem = "minecraft:iron_pickaxe"
	#Is the digging blacklist inverted? [default: false]
	diggingBlacklistInverted = false
	#Digging mobs require the proper tools to dig [default: true]
	diggingRequiresTools = true
	#How common demolition variants are [default: 0.1]
	#Range: 0.0 ~ 1.0
	demolitionChance = 0.1
	#List of mobs that can drop live TNT [default: [minecraft:zombie]
	demolitionMobs = ["minecraft:zombie"]
	#List of mobs that can pillar up and build stairs [default: [minecraft:zombie]
	buildingMobs = ["minecraft:zombie"]
	#If mobs should be allowed to grief blocks [default: false]
	griefing = false
	#List of mobs that aren't allowed to grief
	griefingBlacklist = []
	#If mobs should be allowed to grief all light emitting blocks [default: true]
	griefLightSources = true
	#What blocks will be targeted for destruction when idle (Format: 'minecraft:wool' prefix with # if mentioning a block tag)
	griefableBlocks = ["minecraft:chest", "minecraft:furnace", "minecraft:crafting_table", "#minecraft:fence_gates", "minecraft:melon_block", "minecraft:pumpkin", "#forge:glass", "#forge:glass_panes", "#forge:stained_glass", "#forge:stained_glass_panes", "#minecraft:crops", "minecraft:brewing_stand", "minecraft:enchanting_table", "minecraft:cake", "minecraft:ladder", "#minecraft:wooden_doors", "minecraft:farmland", "minecraft:bookshelf", "#minecraft:saplings", "#minecraft:beds", "#minecraft:fences", "#minecraft:planks"]
	#List of blocks that mobs can pillar with [default: [minecraft:cobblestone]
	pillarBlocks = ["minecraft:cobblestone"]
	#If mobs should be allowed to jump/leap at their target [default: false]
	jumping = true
	#The height the mobs reach when jumping [default: 0.4]
	#Range: 0.01 ~ 8.0
	jumpHeight = 0.4
	#List of mobs that can jump/leap at their target [default: [minecraft:zombie]
	jumpingMobs = ["minecraft:zombie"]
	#If mobs should be allowed to target blocks for the mobs to actively target [default: true]
	blockTargeting = true
	#If the block targeting should be as important as targeting entities (When enabled the goal gets added to the targetSelector instead of the goalSelector) [default: true]
	targetBlocksImportance = false
	#List of mobs that can actively target blocks [default: [minecraft:zombie]
	targetingMobs = ["minecraft:zombie"]
	#What blocks will be targeted for removal when idle (Format: 'minecraft:wool' prefix with # if mentioning a block tag)
	blockTargets = ["#minecraft:candles"]

#Other settings
[Other]
	#The factor by which mob health and damage multipliers will be increased when bosses are killed [default: 0.1]
	#Range: 0.0 ~ 1.7976931348623157E308
	bossKillModifier = 0.1
	#The upper limit of the Boss Kill Modifier [default: 3.0]
	#Range: 0.0 ~ 1.7976931348623157E308
	bossModifierCap = 3.0
	#Debug mob targeting by printing the targeting out [default: false]
	debugTargets = false
	#List of custom potion types witches can throw (id:duration:lvl) [default: [minecraft:harming:1:0, minecraft:slowness:200:0, minecraft:blindness:200:0, minecraft:poison:200:0, minecraft:weakness:200:1, minecraft:mining_fatigue:200:2] ]
	witchPotions = ["minecraft:harming:1:0", "minecraft:slowness:200:0", "minecraft:blindness:200:0", "minecraft:poison:200:0", "minecraft:weakness:200:1", "minecraft:mining_fatigue:200:2"]
	#Allows Enderman to teleport the player instead of themselves [default: true]
	enderPlayerTeleport = true
	#The chance a Spider will web its target to the ground [default: 0.25]
	#Range: 0.0 ~ 1.0
	webbingChance = 0.25
	#Dying to zombies will turn your corpse into one of them [default: true]
	infectiousZombies = true

#Creeper settings
[Creepers]
	#Ignores the listing and allows any mob to have a Creeper rider [default: true]
	allCreeperJockeys = true
	#Creepers will attempt to blast through walls [default: true]
	breaching = true
	#AND HIS NAME IS... [default: 0.01]
	#Range: 0.0 ~ 1.0
	cenaChance = 0.01
	#The chance a Creeper will spawn riding another mob [default: 0.1]
	#Range: 0.0 ~ 1.0
	creeperJockeyChance = 0.1
	#A list of mobs which can become Creeper Jockeys
	creeperJockeyMobs = []
	#Creeper detonations leave behind flaming craters [default: true]
	napalm = true
	#A list of mobs which when exploded generate napalm
	napalmMobs = ["minecraft:creeper"]
	#The chance a Creeper will spawn pre-powered [default: 0.1]
	#Range: 0.0 ~ 1.0
	poweredRarity = 0.1
	#Creepers will continue approaching their target while arming [default: true]
	walkingFuse = true

#Skeletons settings
[Skeletons]
	#How likely Skeletons are to miss their target [default: 0]
	#Range: > 0
	arrowError = 0
	#How far away can Skeletons shoot from [default: 64]
	#Range: > 1
	fireDistance = 64
	#How far away can Skeletons shoot from [default: 64]
	#Range: 0.0 ~ 1.0
	witherSkeletonChance = 0.1
	#Effects that Skeleton arrows can have (id:duration:lvl) [default: [minecraft:slowness:60:0]
	arrowTips = ["minecraft:slowness:60:0"]

#Attribute settings
[Attributes]
	#Health modifier [default: 1.0]
	#Range: 0.0 ~ 1.7976931348623157E308
	healthModifier = 1.0
	#Damage modifier [default: 1.0]
	#Range: 0.0 ~ 1.7976931348623157E308
	damageModifier = 1.0
	#Speed modifier [default: 1.0]
	#Range: 0.0 ~ 1.7976931348623157E308
	speedModifier = 1.0
	#Knockback modifier [default: 1.0]
	#Range: 0.0 ~ 1.7976931348623157E308
	knockbackModifier = 1.0
	#Boss Health modifier [default: false]
	bossHealthModifier = false
	#Boss Damage modifier [default: false]
	bossDamageModifier = false
	#Boss Speed modifier [default: false]
	bossSpeedModifier = false
	#Boss Knockback modifier [default: false]
	bossKnockbackModifier = false

#Game Stages support
[GameStages]
	#The stage required until mobs can dig through blocks [empty = disabled]
	diggerStage = ""
	#The stage required until mobs can drop live TNT [empty = disabled]
	demolitionStage = ""
	#The stage required until mobs can pillar up and build stairs [empty = disabled]
	buildingStage = ""
	#The stage required until mobs can grief blocks [empty = disabled]
	griefingStage = ""
	#The stage required until creeper jockeys can spawn [empty = disabled]
	creeperJockeyStage = ""
	#The stage required until mobs can jump at their target [empty = disabled]
	jumpingStage = ""
	#The stage required until mobs can actively target blocks [empty = disabled]
	blockTargetingStage = ""

